export declare const MAKE_STATE_DIR: string;
export declare const MAKE_CONFIG_RELATIVE_PATH: string;
export declare const MAKE_ENTRIES_RELATIVE_PATH: string;
export declare const MAKE_RUNTIME_SERVER_INFO_RELATIVE_PATH: string;
export declare const MAKE_ADMIN_SERVER_INFO_RELATIVE_PATH: string;
export declare const SIDEBAR_TREE_STORE_RELATIVE_PATH: string;
export declare const PROJECT_METADATA_RELATIVE_PATH: string;
export declare const MAKE_CLIENT_MARKER_RELATIVE_PATH: string;
export declare const PROJECT_SESSIONS_RELATIVE_DIR: string;
export declare const PROJECT_EXPORTS_RELATIVE_DIR: string;
export declare const PROJECT_EDIT_HISTORY_RELATIVE_DIR: string;
export declare const GLOBAL_PROJECTS_REGISTRY_FILE_NAME = "projects.json";
export declare const GLOBAL_SERVER_CONFIG_FILE_NAME = "server.config.json";
export declare const GLOBAL_VOICE_ASSISTANT_SETTINGS_FILE_NAME = "voice-assistant.settings.json";
export declare function resolveProjectRoot(projectRoot: string): string;
export declare function getMakeStateDir(projectRoot: string): string;
export declare function getGlobalMakeStateDir(homeDir?: string): string;
export declare function getProjectRegistryPath(homeDir?: string): string;
export declare function getGlobalServerConfigPath(homeDir?: string): string;
export declare function getGlobalVoiceAssistantSettingsPath(homeDir?: string): string;
export declare function getConfigPath(projectRoot: string): string;
export declare function getEntriesManifestPath(projectRoot: string): string;
export declare function getRuntimeServerInfoPath(projectRoot: string): string;
export declare function getGlobalAdminServerInfoPath(homeDir?: string): string;
export declare function getAdminServerInfoPath(_projectRoot?: string, options?: {
    homeDir?: string;
}): string;
export declare function getSidebarTreeStorePath(projectRoot: string): string;
export declare function getProjectMetadataPath(projectRoot: string): string;
export declare function getMakeClientMarkerPath(projectRoot: string): string;
export declare function getProjectSessionsDir(projectRoot: string): string;
export declare function getProjectExportsDir(projectRoot: string): string;
export declare function getProjectEditHistoryDir(projectRoot: string): string;
