export const STALE_AGENT_BRIDGE_QUERY_PARAMS = [
  'agentApiBaseUrl',
  'apiBaseUrl',
  'agentIntegrationChannel',
  'integrationChannel',
  'agentTargetClientId',
  'integrationClientId',
  'cwd',
  'workdir',
  'provider',
  'tool',
  'targetPath',
  'context',
  'editorIntegrationWs',
  'editorApiBaseUrl',
  'editorIntegrationChannel',
  'editorClientId',
  'editorSessionId',
  'editorPageUrl',
  'editorMobileMode',
  'mobileMode',
  'makeServerOrigin',
  'agentToolbar',
  'annotationSession',
  'inspecta',
] as const;
